# Generated by Django 5.0.1 on 2024-01-28 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='district',
            table='districts',
        ),
        migrations.AlterModelTable(
            name='province',
            table='provinces',
        ),
        migrations.AlterModelTable(
            name='regency',
            table='regencies',
        ),
        migrations.AlterModelTable(
            name='subdistrict',
            table='sub_districts',
        ),
        migrations.AlterModelTable(
            name='village',
            table='villages',
        ),
    ]
